version: '3.8'
services:
  web1: &web
    build: .
    hostname: web01
    ports: 
      - "8081:8080"
    environment:
      - DB_HOSTNAME=db
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "180MB"

  web2:
    <<: *web 
    hostname: web02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"  
    depends_on:
      - web1
      - web2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "0.15" 
          memory: "50MB" 

  db:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data  
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "0.35" 
          memory: "270MB"  

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
    name: rinha
